name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
           aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
           aws-region: us-east-1
    - name: On-demand self-hosted AWS EC2 runner for GitHub Actions
      uses: machulav/ec2-github-runner@v2
      with:
         github-token: ${{secrets.TOKEN}}
         ec2-image-id: ami-00399ec92321828f5
         ec2-instance-type: t2.micro
         subnet-ID: subnet-cdd1e581
         security-group-id: sg-02c9fc79b6c4109d7
         mode: start
         aws-resource-tags: '[{"Key": "Name" , "Value": "productcrud.ca"}]'
         ec2-instance-id: i-03d221ab975187baf
    - uses: actions/checkout@v2
    - name: Changing directory
      run: cd /var/www
    - name: Update repository
      run: git pull origin master
    
