name: Deploy test

on:
  push:
    branches: [ branch1 ]
  pull_request:
    branches: [ branch1 ]
  
    
jobs:
    build:
      runs-on: ubuntu-latest
      
      steps:
        - uses: actions/checkout@v2

        - name: On-demand self-hosted AWS EC2 runner for GitHub Actions
          uses: machulav/ec2-github-runner@v2
          with:
             github-token: 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
             ec2-image-id: ami-00399ec92321828f5
             ec2-instance-type: t2.micro
             subnet-ID: subnet-cdd1e581
             security-group-id: sg-02c9fc79b6c4109d7
             mode: start
             aws-resource-tags: '[{"Key": "Name" , "Value": "productcrud.ca"}]'
             ec2-instance-id: i-03d221ab975187baf

        - name: Changing directory
          run: cd /var/www

        - name: Clone repository
          run: git clone 

        - name: Install Dependencies
          run: composer update

        - name: Generate key
          run: php artisan key:generate

        - name: Directory Permissions
          run: chmod -R 777 storage bootstrap/cache

        - name: Migrating Database
          env:
           DB_CONNECTION: mysql
          run: php artisan migrate
    
